name: Deploy Application with Approval

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build application
        run: echo "Building the application..."

  staging-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to staging
        run: echo "Deploying to staging..."

  production-deploy:
    runs-on: ubuntu-latest
    needs: staging-deploy
    environment:
      name: production  # This matches the environment in your GitHub settings
    steps:
      - name: Deploy to production
        run: echo "Deploying to production..."
